language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x

before_install:
  - go get -u github.com/kardianos/govendor
  - go get -u golang.org/x/lint/golint

env:
  - CONSUL_VERSION=1.4.5 CONSUL_DOWNLOAD_URL=https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip

install:
  - wget ${CONSUL_DOWNLOAD_URL}
  - unzip ./consul_${CONSUL_VERSION}_linux_amd64.zip
  - cp ./consul ${HOME}/gopath/bin/consul

after_success:
  - bash <(curl -s https://codecov.io/bash)