language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

before_install:
  - go get -u github.com/kardianos/govendor
  - go get -u github.com/golang/lint/golint

env:
  - CONSUL_VERSION=0.8.5 CONSUL_DOWNLOAD_URL=https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_arm64.zip
  - GOOS=linux
  - GOARCH=amd64
install:
  - wget ${CONSUL_DOWNLOAD_URL}
  - unzip ./consul_${CONSUL_VERSION}_linux_arm64.zip
  - cp ./consul ${HOME}/gopath/bin/consul